services:
  backend:
    image: api:latest
    build:
      context: ./api
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      #- DB_SERVER=host.docker.internal #solo para pruebas db local
      - NODE_ENV=production
      - ALLOWED_ORIGIN=http://${DOMAIN}:${CLIENT_PORT}
      - PORT=3000
    env_file: ./api/.env

  client:
    image: web:latest
    build:
      context: ./frontend
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - VITE_API_URL=http://${DOMAIN}:${BACKEND_PORT}
    # env_file: ./frontend/.env