services:
  backend:
    image: api:latest
    build:
      context: ./api
    ports:
      - "${BACKEND_PORT}:3000"
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-${DOMAIN}:${CLIENT_PORT}}
    env_file:
      - .env
  client:
    image: web:latest
    build:
      context: ./frontend
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - VITE_API_URL=${DOMAIN}:${BACKEND_PORT}